[target.aarch64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install -y --no-install-recommends libasound2-dev:arm64"
]

[target.aarch64-unknown-linux-musl.env]
PKG_CONFIG_PATH = { value = "/usr/lib/aarch64-linux-gnu/pkgconfig" }

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y --no-install-recommends libasound2-dev"
]
