name: Cross-platform Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - os-name: Windows
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: Windows ARM
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc

          - os-name: macOS
            runs-on: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ALSA dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release --bin under_term"
          strip: true
          cc-args: "-D__ARM_NEON__"

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: under_term
          target: ${{ matrix.platform.target }}
          changes-file: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
